ALTER DATABASE [cdc_testing] SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE [cdc_testing] SET
  CHANGE_TRACKING = ON (
    CHANGE_RETENTION = 2 DAYS ,
    AUTO_CLEANUP = ON
);

ALTER TABLE [cdc_testing].[dbo].[binary_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[varbinary_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[image_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[float_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[real_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[char_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[varchar_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[text_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[nchar_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[nvarchar_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[ntext_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[bigint_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[int_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[smallint_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[tinyint_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[smallmoney_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[money_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[decimal_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[numeric_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[date_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[datetime_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[datetime2_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[time_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [cdc_testing].[dbo].[smalldatetime_table] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);

ALTER TABLE [cdc_testing].[dbo].[users] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);